ecomm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/',
         include(('products.urls', 'products'), namespace='products')),
    path('api/',
         include(('rest_api.urls', 'rest_api'), namespace='rest_api')),
]

products/urls.py
from django.urls import path

from products import views

urlpatterns = [
    path('list/', views.list_products, name='list'),
    path('create/', views.create_product, name='create'),
    path('update/<int:product_id>', views.update_product, name='update'),
    path('delete/<int:product_id>', views.delete_product, name='delete'),
]

products/models.py
from django.db import models
from django.db.models import (
    Q,
    QuerySet
    )


class ProductManager(models.Manager):
    def with_text(self, text: str) -> QuerySet:
        '''
            Pesquisa nos produtos cujo filtro seja **"text"**.
            
            :param text: Texto que será usado na pesquisa.

            :return: QuerySet com o filtro aplicado.
        '''
        queryset = self.get_queryset().filter(name__contains=text)
        return queryset
    
    def expensive_products(self) -> QuerySet:
        '''
            Filtro de produtos cujo preço seja maior que 500,00
        '''
        return self.get_queryset().filter(price__gte=500)

    def cheap_products(self) -> QuerySet:
        '''
            Retorna a lista dos produtos mais baratos.
        '''
        return self.get_queryset().filter(
            category__name__contains='categoria',
            price__lte=15
        )

    def cat1_or_expensive_products(self) -> QuerySet:
        '''
            Retorna a lista dos produtos mais caros de uma determinada categoria.
        '''
        query_filter = Q(category__name='Categoria 1') | Q(price__gte=500)
        queryset = self.get_queryset().filter(query_filter)

        print(queryset.query)
        return queryset
    
    def test_fiunction(self):
        self.with_text('')
        self.expensive_products('')
        self.cheap_products('') 
        self.cat1_or_expensive_products('')


class Category(models.Model):
    name = models.CharField(verbose_name='Categoria',
                            max_length=50,
                            blank=False,
                            null=False)

    description = models.TextField(verbose_name='Descrição',
                                   max_length=200,
                                   blank=True,
                                   null=True)

    def __str__(self):
        return f'{self.name}'
    
    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = 'Categorias'


# Create your models here.
class Product(models.Model):
    '''
        Model contendo todos os campos necessários
        para o cadastro de produtos no ecomm.
    '''
    objects = ProductManager()
    name = models.CharField(verbose_name='Nome',
                            max_length=100,
                            blank=False,
                            null=False)

    description = models.TextField(verbose_name='Descrição',
                                   max_length=200,
                                   blank=True,
                                   null=True)

    price = models.DecimalField(verbose_name='Preço',
                                max_digits=8,
                                decimal_places=2,
                                blank=False,
                                null=False)

    category = models.ForeignKey(Category,
                                 verbose_name='Categoria',
                                 on_delete=models.DO_NOTHING,
                                 related_name='products')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'


class Order(models.Model):
    PAYMENT_CHOICES = [
        ('dinheiro', 'Dinheiro'),
        ('credito', 'Cartão de Crédito'),
        ('debito', 'Cartão de Débito')
    ]
    name = models.CharField(verbose_name='Nome',
                            max_length=100,
                            blank=False,
                            null=False)
    payment = models.CharField(verbose_name='Forma de Pagamento',
                               max_length=50,
                               choices=PAYMENT_CHOICES,
                               blank=False,
                               null=False,
                               help_text='Formas de pagamento')
    products = models.ManyToManyField(Product)
    
    @property
    def total_amount(self):
        return sum([product.price for product in self.products.all()])

    def __str__(self):
        return f'{self.name} - {self.total_amount}'

    class Meta:
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'

products/forms.py
from django import forms
from products.models import Product

class ProductModelForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'category']

products/views.py
from django.shortcuts import render, redirect
# from django.views.decorators.cache import cache_page
from django.conf import settings

from products.models import Product
from products.forms import ProductModelForm

# Create your views here.

# @cache_page(settings.CACHE_TTL)
def list_products(request):
    products = Product.objects.all()

    context = {
        'products': products,
    }

    return render(request, 'products/list.html', context=context)

def create_product(request):
    if request.method == 'POST':
        form = ProductModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('products:list')
    else:
        form = ProductModelForm()

    context = {
        'form': form
    }
    return render(request, 'products/create.html', context=context)

def update_product(request, product_id):
    search_product_id = Product.objects.get(pk=product_id)

    if request.method == 'POST':
        form = ProductModelForm(data=request.POST, instance=search_product_id)
        
        if form.is_valid():
            form.save()
            return redirect('products:list')

    else:
        form = ProductModelForm(instance=search_product_id)

        if form.is_valid():
            name = form.cleaned_data['name']
            description = form.cleaned_data['description']
            price = form.cleaned_data['price']
            category = form.cleaned_data['category']

            product_updated = Product(name=name,
                                      description=description,
                                      price=price,
                                      category=category)
                                      
            Product(product_updated)

    context = {
        'form': form,
    }

    return render(request, 'products/create.html', context=context)

def delete_product(request, product_id):
    search_product_id = Product.objects.get(pk=product_id)
    search_product_id.delete()
    
    return redirect('products:list')

products/templates/products/create.html
{% extends 'base.html' %} {% block title %} {{block.super}} Inserir {% endblock title %} {% block content %}
<div class="row">
    <div class="col-md-9">
        <h1>Adicionar produto</h1>
    </div>
</div>
<form action="" method="post">
    {% csrf_token %} {% for field in form %}
    <div class="form-group row">
        <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
        <div class="col-sm-10">
            {{ field }}
        </div>
        {% if field.errors %} {% for error in field.errors %}
        <div class="offset-sm-2 col-sm-10">
            <span class="badge badge-pill badge-danger">{{ error }}</span>
        </div>
        {% endfor %} {% endif %}
    </div>
    {% endfor %}
    <div class="row justify-content-end">
        <div class="col-md-2">
            <button class="btn btn-primary btn-block" type="submit"><i class="fa fa-check" aria-hidden="true"></i> Salvar</button>
        </div>
    </div>
</form>
{% endblock content %}

products/templates/products/list.html
{% extends 'base.html' %} {% block title %} {{ block.super }} Listagem {% endblock title %} {% block content%}
<div class="row">
    <div class="col-md-9">
        <h1>Lista de Produtos</h1>
    </div>
    <div class="col-md-3">
        <a class="btn btn-primary btn-block" href="{% url 'products:create' %}"><i class="fa fa-plus-circle"></i> Adicionar Produto</a>
    </div>
    <table class="table table-bordered table-hover">
        <thead>
            <tr class="table-active">
                <th>Nome</th>
                <th>Descrição</th>
                <th>Preço(R$)</th>
                <th>Categoria</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for product in products%}
            <tr>
                <td>{{ product.name | capfirst }}</td>
                <td>{{ product.description }}</td>
                <td>{{ product.price }}</td>
                <td>{{ product.category }}</td>
                <td align="center" width="100px">
                    <a href="{% url 'products:update' product.pk %}">
                        <i class="fa fa-edit" title="Editar"></i>
                    </a>
                    &nbsp;<span style="color: blue;">|</span> &nbsp;
                    <a href="{% url 'products:delete' product.pk %}">
                        <i class="fa fa-trash" title="Excluir"></i>
                    </a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="5" class="text-center">
                    Não existem itens a serem exibidos.
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content%}